services:
  backend_api:
    container_name: backend_api
    image: huntergrimes/backend_api:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
      - RIOT_API_KEY=RGAPI-797d6a18-d2d0-431d-878f-be1d8b5d5987
    depends_on:
      - flask_db

  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
